# Generated by Django 5.0.4 on 2024-04-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appReRu', '0003_remove_shippingaddress_zipcode_shippingaddress_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='order_notes',
            field=models.TextField(null=True),
        ),
    ]
