# Generated by Django 5.0.4 on 2024-04-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appReRu', '0004_shippingaddress_order_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('link', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('title1', models.CharField(blank=True, max_length=100, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('link1', models.URLField(blank=True, null=True)),
                ('description1', models.TextField(blank=True, null=True)),
                ('title2', models.CharField(blank=True, max_length=100, null=True)),
                ('image2', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('link3', models.URLField(blank=True, null=True)),
                ('description3', models.TextField(blank=True, null=True)),
                ('title4', models.CharField(blank=True, max_length=100, null=True)),
                ('image4', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('link4', models.URLField(blank=True, null=True)),
                ('description4', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
