# Generated by Django 5.0.4 on 2024-04-18 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appReRu', '0005_advertisement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('link', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('link', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('link', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='description1',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='description3',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='description4',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='link1',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='link3',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='link4',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='title1',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='title2',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='title4',
        ),
    ]
