# Generated by Django 5.0.4 on 2024-04-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appReRu', '0007_contact_contactus_faqshelp_oursocials_privacypolicy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('fulfilled', 'Fulfilled'), ('unfulfilled', 'Unfulfilled')], default='unfulfilled', max_length=20),
        ),
    ]
