# Generated by Django 5.0.4 on 2024-04-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appReRu', '0009_completedorder_fulfilledorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ("Men's Fashion", "Men's Fashion"), ("Women's Fashion", "Women's Fashion"), ('Home & Kitchen', 'Home & Kitchen'), ('Beauty & Personal Care', 'Beauty & Personal Care'), ('Health & Wellness', 'Health & Wellness'), ('Sports & Outdoors', 'Sports & Outdoors'), ('Books & Stationery', 'Books & Stationery'), ('Toys & Games', 'Toys & Games'), ('Automotive', 'Automotive'), ('Furniture & Decor', 'Furniture & Decor'), ('Food & Beverages', 'Food & Beverages'), ('Baby & Kids', 'Baby & Kids'), ('Pet Supplies', 'Pet Supplies'), ('Tools & Home Improvement', 'Tools & Home Improvement'), ('Office Supplies', 'Office Supplies'), ('Jewelry & Watches', 'Jewelry & Watches'), ('Travel & Luggage', 'Travel & Luggage'), ('Musical Instruments', 'Musical Instruments'), ('Art & Craft Supplies', 'Art & Craft Supplies'), ('Party Supplies', 'Party Supplies')], max_length=100),
        ),
    ]
