# Generated by Django 5.0.4 on 2024-04-21 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appReRu', '0011_remove_product_categories_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unique_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
