# Generated by Django 5.0.4 on 2024-05-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appReRu', '0014_userinbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinbox',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
