# Generated by Django 5.0.4 on 2024-05-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appReRu', '0015_userinbox_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
