# Generated by Django 5.0.4 on 2024-05-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appReRu', '0016_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability_status',
            field=models.CharField(choices=[('available', 'Available'), ('sold_out', 'Sold Out')], default='available', max_length=20),
        ),
    ]
