# Generated by Django 5.0.4 on 2024-05-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appReRu', '0020_deliveryfee_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='details',
            new_name='details_1',
        ),
        migrations.AddField(
            model_name='product',
            name='details_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='details_3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
